version: '3'
services: 
    jekyll:
        image: jekyll/jekyll
        ports: 
            - 4000:4000
        volumes: 
            - .:/srv/jekyll
        command: bash -c "bundle && bundle exec jekyll serve --host=0.0.0.0"
        # entrypoint: ["bundle", "bundle exec jekyll serve --host=0.0.0.0"]
        restart: unless-stopped